services:
  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - api
      - front
    environment:
      - API_PORT=${API_PORT} 
      - FRONT_PORT=${FRONT_PORT}

  api:
    build:
      context: .                           
      dockerfile: apps/doramar-api/Dockerfile     
    container_name: doramar-api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env  
    command: pm2-runtime ecosystem.config.js
    environment:
      DATABASE_URL: "${DATABASE_URL}"

  front:
    build:
      context: .                     
      dockerfile: apps/doramar-web/Dockerfile    
      args: 
        - API_URL=${API_URL}
        - FIREBASE_API_KEY=${FIREBASE_API_KEY}
        - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
        - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
        - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
        - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
        - FIREBASE_APP_ID=${FIREBASE_APP_ID}
    container_name: doramar-web 
    depends_on:
      - api
    env_file:    
      - .env